---
title: "Predicting of the pulmunary TB cases , Uganda"
author: "Patrick Kaggwa"
date: "12/03/2024"
output: html_document
---


```{r}
# load the relevant tidymodels libraries
library(here) #for data loading/saving
library(tidyverse) #for data management
library(tidymodels) #for data modeling
library(skimr) #for variable summaries
library(broom.mixed) #for converting bayesian models to tidy tibbles
library(glmnet) #for lasso models
library(doParallel) #for parallel backend for tuning processes
library(ranger) #for random forest models
library(rsample)

```



## Load the data.

```{r}
#Path to data. Note the use of the here() package and not absolute paths
data_location <- here::here("data","processed-data","madaproject.rds")
#load data
# Loading the needed dataset
madaproject <- readRDS(data_location)

```


Before I start doing some model building I split the data into training and testing datasets.

```{r}
set.seed(123)
data_split <- initial_split(madaproject, prop = 0.7)
data_train <- training(data_split)
data_test <- testing(data_split)
```


```{r}
set.seed(123)
folds <- vfold_cv(data_train, strata = tb)
```


I will define my recipe using a recipe package under tidy models
```{r}
rec <- logistic_reg()
tb_recipe <- recipe(tb ~ ., data = data_train) %>%
  step_dummy(all_nominal_predictors())
  
```

```{r}
tb_workflow <- workflow(tb_recipe, log_model)
```


defining our logistic model
```{r}
doParallel::registerDoParallel()
ctrl_preds <- control_resamples(save_pred = TRUE)
samplefit <- fit_resamples(tb_workflow, folds, control = ctrl_preds)

```

```{r}
#augment(samplefit) %>%
#  roc_curve(tb, .pred_TB)  %>%
#  autoplot()
```




